### ISSUE TITLE
Use public development server

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-demo#1]
The following settings can be used as default (or alternatively added to the readme file).

Address: `wss://server.saltyrtc.org:9287`
Public permanent key: `f77fe623b6977d470ac8c7bf7011c4ad08a1d126896795db9d2b4b7a49ae1045`

**Comment by dbrgn** [comment]
Are you hosting that server?

**Comment by lgrahl** [comment]
Yep.

**Comment by dbrgn** [comment]
There's no STUN/TURN server running though, right?

**Comment by lgrahl** [comment]
I have a TURN server running but would rather not use it in the demo.
