### ISSUE TITLE
Missing Dependencies (Web)

### ISSUE THREAD

**Issue by lgrahl** [saltyrtc/saltyrtc-demo#2]
After `npm install`, the web version is missing the following dependencies:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///saltyrtc-demo/web/node_modules/chunked-dc/dist/chunked-dc.es5.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///saltyrtc-demo/web/node_modules/msgpack-lite/dist/msgpack.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///saltyrtc-demo/web/node_modules/chunked-dc/dist/chunked-dc.es5.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
```

Not sure if this is good practice, but they can be retrieved by changing the paths in `index.html`:

```
        <script src="node_modules/webrtc-adapter/out/adapter_no_edge.js"></script>
        <script src="node_modules/saltyrtc-client/node_modules/msgpack-lite/dist/msgpack.min.js"></script>
        <script src="node_modules/tweetnacl/nacl-fast.min.js"></script>
        <script src="node_modules/saltyrtc-task-webrtc/node_modules/chunked-dc/dist/chunked-dc.es5.min.js"></script>
        <script src="node_modules/saltyrtc-client/dist/saltyrtc-client.es5.js"></script>
        <script src="node_modules/saltyrtc-task-webrtc/dist/saltyrtc-task-webrtc.es5.js"></script>
```

**Comment by dbrgn** [comment]
I cannot reproduce this. Maybe you have a wildly different npm version? I'm on 4.0.2.

**Comment by lgrahl** [comment]
Have you removed `node_modules` entirely before trying it again?

My version is bleeding edge `1.3.10` due to Ubuntu 14. :grin: Have to test it on my notebook later this evening.

**Comment by dbrgn** [comment]
> Have you removed node_modules entirely before trying it again?

Yes.

But I can reproduce your issue with this Dockerfile:

```dockerfile
FROM ubuntu:14.04

RUN apt-get update && apt-get install -y nodejs npm git
RUN git clone https://github.com/saltyrtc/saltyrtc-demo
RUN cd saltyrtc-demo/web && npm install

CMD /bin/bash -c "node --version && npm --version && ls -la saltyrtc-demo/web/node_modules/chunked-dc/dist/chunked-dc.es5.min.js"
```

> $ docker build . -t demo && docker run demo
> 1.3.10
> ls: cannot access saltyrtc-demo/web/node_modules/chunked-dc/dist/chunked-dc.es5.min.js: No such file or directory

Same thing with npm 2.15.11:

```dockerfile
FROM node:4

RUN git clone https://github.com/saltyrtc/saltyrtc-demo
RUN cd saltyrtc-demo/web && npm install

CMD /bin/bash -c "nodejs --version && npm --version && ls -la saltyrtc-demo/web/node_modules/chunked-dc/dist/chunked-dc.es5.min.js"
```

It works with npm 3.10.8 though:

```dockerfile
FROM node:6

#RUN apt-get update && apt-get install -y nodejs npm git
RUN git clone https://github.com/saltyrtc/saltyrtc-demo
RUN cd saltyrtc-demo/web && npm install

CMD /bin/bash -c "nodejs --version && npm --version && ls -la saltyrtc-demo/web/node_modules/chunked-dc/dist/chunked-dc.es5.min.js"
```

Not sure what the best way to solve this would be though. Ubuntu 16.04 ships npm 3.5.2 though, so I'd probably recommend to use a PPA.

**Comment by dbrgn** [comment]
Maybe there's a way to set the dependency nesting behavior with command line options?

**Comment by lgrahl** [comment]
That would be great but I haven't found anything in the web so far. Otherwise, we can simply add a note that we require npm 3.x.x.

**Comment by dbrgn** [comment]
There's [this](https://stackoverflow.com/questions/33321181/how-can-i-force-npm-3-to-install-nested-dependencies), but I don't think it's appropriate for our use case.

**Comment by lgrahl** [comment]
Nah, you've added a note to the readme. Should be fine. :)
